version: "3"

services:
  api-pasteur:
    container_name: api-pasteur
    restart: always
    build: .
    environment:
      - "VIRTUAL_HOST=lora.agicquel.com"
      - "VIRTUAL_PORT=8080"
      - "LETSENCRYPT_HOST=lora.agicquel.com"
      - "LETSENCRYPT_EMAIL=antoine.gicquel@mailoo.org"
    network_mode: bridge

